markdown: kramdown
host: 127.0.0.1
kramdown:
  parse_block_html: true
name: Benina
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge

sass:
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /actueel/:path/
site:
  title: Stichting Benina

title: Stichting Benina
description: >- # this means to ignore newlines until "baseurl:"
  Stichting Benina is opgericht met het doel cultuur in de meest algemene zin van het woord te bevorderen. Specifieke activiteiten van de stichting betreffen het mogelijk maken van artistieke filmprojecten, creatieve cursussen met het doel creativiteit te ontplooien, voor iedereen toegankelijk. De stichting heeft geen winstoogmerk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.benina.nl" # the base hostname & protocol for your site, e.g. http://example.com

repos:
- name: stichting-benina.github.io
  description: Stichting Benina
  url: https://github.com/stichting-benina/stichting-benina.github.io

plugins:
  - jekyll-last-modified-at
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed

google_analytics_ua: UA-127597737-1
